print("My Daily Routine")
print("I wake up at 6:30 am in the morning.")
print("Then, I for for my swimming class from 7 a.m. to 8 a.m.")
print("I go to school directly after swimming.")
print("My school hours are 8 a.m. to 2:15 p.m.")
print("I return home by 2:35 p.m. After that I have my lunch along with watching my favourite T.V show which is 'Young sheldon'.")
print("I rest for half an hour after that.\n I go to attend my tuition from 4 p.m. to 5 p.m.")
print("I complete all my homework till 8p.m., after coming back from the class.")
print("My dad reaches home from office by 8p.m. Then we have dinner.")
print("I self-study for an hour after having dinner.")
print("Then we spend some family time together.")
print("I sleep by 11 p.m. ")
Num1 = int(7)
Num2 = int(4)
Ans = Num1*Num2
print("My total study time in a week:",Ans,"hours")